spring:
  application:
    name: QuoraApp

  data:
    mongodb:
      host: localhost
      port: 27017
      database: quora_db
      auto-index-creation: true

    elasticsearch:
      repositories:
        enabled: true


  elasticsearch:
    uris: http://localhost:9200